import polib
import os

# --- Configuration ---
# The new template file generated by Babel
pot_file_path = 'app/messages.pot'
# The old PO file that contains the translations you want to keep
po_file_path = 'app/translations/es_ES/LC_MESSAGES/messages.po'
# The output file. We'll write the merged content here.
output_file_path = 'app/messages.pot.new'
# --- End Configuration ---

try:
    # Load the .po file and create a dictionary of existing translations
    po = polib.pofile(po_file_path)
    translations = {entry.msgid: entry.msgstr for entry in po if entry.msgstr}
    print(f"Found {len(translations)} translations in {os.path.basename(po_file_path)}")

    # Load the new .pot template file
    pot = polib.pofile(pot_file_path)
    print(f"Found {len(pot)} entries in {os.path.basename(pot_file_path)}")

    # Update the .pot file entries with translations from the .po file
    updated_count = 0
    for entry in pot:
        if not entry.msgstr and entry.msgid in translations:
            entry.msgstr = translations[entry.msgid]
            updated_count += 1

    # Save the result to a new file
    pot.save(output_file_path)

    print(f"\nSuccessfully merged translations.")
    print(f"Updated {updated_count} entries.")
    print(f"New file saved to: {output_file_path}")
    print(f"\nPlease review '{os.path.basename(output_file_path)}' and if it looks correct, rename it to 'messages.pot'.")

except FileNotFoundError as e:
    print(f"Error: File not found - {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")
