# En este archivo se definen las constantes para los tipos de logs

log_actions = {
    'user_login': 'USER_LOGIN',
    'type_create': 'TYPE_CREATE',
    'type_update': 'TYPE_UPDATE',
    'type_delete': 'TYPE_DELETE',
    'form_create': 'FORM_CREATE',
    'form_update': 'FORM_UPDATE',
    'form_duplicate': 'FORM_DUPLICATE',
    'form_delete': 'FORM_DELETE',
    'list_create': 'LIST_CREATE',
    'list_update': 'LIST_UPDATE',
    'list_delete': 'LIST_DELETE',
    'resource_create': 'RESOURCE_CREATE',
    'resource_update': 'RESOURCE_UPDATE',
    'resource_delete': 'RESOURCE_DELETE',
    'resource_open': 'RESOURCE_OPEN',
    'record_create': 'RECORD_CREATE',
    'record_update': 'RECORD_UPDATE',
    'record_delete': 'RECORD_DELETE',
    'record_get_all': 'RECORD_GET_ALL',
    'system_update': 'SYSTEM_UPDATE',
    'snap_create': 'SNAP_CREATE',
    'snap_delete': 'SNAP_DELETE',
    'view_create': 'VIEW_CREATE',
    'view_update': 'VIEW_UPDATE',
    'view_delete': 'VIEW_DELETE',
    'docseg_extraction': 'DOCSEG_EXTRACTION',
    'av_transcribe': 'AV_TRANSCRIBE',
    'lt_extraction': 'LT_EXTRACTION',
}
